# Numpy operations

In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3,4])
b=np.arange(5)
c=np.linspace(0,1,5)

In [7]:
c

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
a=np.array([[1,2,3],[4,6,7]])
print(a[0][1])
a=a.reshape(3,2)

2

In [11]:
print(a)

[[1 2]
 [3 4]
 [6 7]]

In [20]:
# np.mean(a)
print(np.std(a))
print(np.sum(a))
print(np.dot(a,a))

2.1147629234082532
23

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [21]:
import pandas as pd

In [22]:
df=pd.read_csv('sales_data.csv')

In [23]:
df.head()

         date region product   sales  profit
0  2024-01-01  North      TV  1000.0     200
1  2024-01-02  South  Laptop  1500.0     300
2  2024-01-03   East  Mobile   800.0     150
3  2024-01-04   West  Tablet     NaN     120
4  2024-01-05  North  Mobile  1200.0     250

In [24]:
df.tail()

         date region product   sales  profit
1  2024-01-02  South  Laptop  1500.0     300
2  2024-01-03   East  Mobile   800.0     150
3  2024-01-04   West  Tablet     NaN     120
4  2024-01-05  North  Mobile  1200.0     250
5  2024-01-06  South      TV     NaN     180

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     6 non-null      object
 1   region   6 non-null      object
 2   product  6 non-null      object
 3   sales    4 non-null      float64
 4   profit   6 non-null      int64
dtypes: float64(1), int64(1), object(3)
memory usage: 372.0+ bytes

In [27]:
#groupimg
region_sales=df.groupby('region')['sales'].sum()
print(region_sales)

region
East      800.0
North    2200.0
South    1500.0
West        0.0
Name: sales, dtype: float64

In [29]:
productsales=df.groupby('product')['sales'].sum()
print(productsales)

product
Laptop    1500.0
Mobile    2000.0
TV        1000.0
Tablet       0.0
Name: sales, dtype: float64

In [30]:
df.head()

         date region product   sales  profit
0  2024-01-01  North      TV  1000.0     200
1  2024-01-02  South  Laptop  1500.0     300
2  2024-01-03   East  Mobile   800.0     150
3  2024-01-04   West  Tablet     NaN     120
4  2024-01-05  North  Mobile  1200.0     250

In [31]:
df.isnull()

    date  region  product  sales  profit
0  False   False    False  False   False
1  False   False    False  False   False
2  False   False    False  False   False
3  False   False    False   True   False
4  False   False    False  False   False
5  False   False    False   True   False

In [32]:
df.fillna(0,inplace=True)

In [33]:
df

         date region product   sales  profit
0  2024-01-01  North      TV  1000.0     200
1  2024-01-02  South  Laptop  1500.0     300
2  2024-01-03   East  Mobile   800.0     150
3  2024-01-04   West  Tablet     0.0     120
4  2024-01-05  North  Mobile  1200.0     250
5  2024-01-06  South      TV     0.0     180

In [34]:
df.dropna(inplace=True)

In [42]:
emp_df=pd.read_csv('employee_data.csv')
sal_df=pd.read_csv('sales_data.csv')
emp_df

   ID     Name Department   Salary    JoinDate
0   1    Alice         HR  50000.0  2022-01-10
1   2      Bob    Finance  60000.0  2023-03-15
2   3  Charlie         IT  55000.0  2021-07-20
3   4    David  Marketing      NaN  2022-11-05
4   5      Eva    Finance  58000.0  2020-05-30

In [47]:
meger_df=pd.merge(emp_df,sal_df,on='ID',how='left')
print(meger_df)

   ID     Name Department   Salary    JoinDate        date region product  \
0   1    Alice         HR  50000.0  2022-01-10  2024-01-01  North      TV
1   2      Bob    Finance  60000.0  2023-03-15  2024-01-02  South  Laptop
2   3  Charlie         IT  55000.0  2021-07-20  2024-01-03   East  Mobile
3   4    David  Marketing      NaN  2022-11-05  2024-01-04   West  Tablet
4   5      Eva    Finance  58000.0  2020-05-30  2024-01-05  North  Mobile

    sales  profit
0  1000.0     200
1  1500.0     300
2   800.0     150
3     NaN     120
4  1200.0     250

In [43]:
sal_df

   ID        date region product   sales  profit
0   1  2024-01-01  North      TV  1000.0     200
1   2  2024-01-02  South  Laptop  1500.0     300
2   3  2024-01-03   East  Mobile   800.0     150
3   4  2024-01-04   West  Tablet     NaN     120
4   5  2024-01-05  North  Mobile  1200.0     250
5   6  2024-01-06  South      TV     NaN     180